### ISSUE TITLE
UI Not updating on State changes [Android]

### ISSUE THREAD

**Issue by Michael24884** [RudolfHladik/Template#2]
Calling use case from a view model returns the data correctly( verified using Logs), but the ui that uses this view model does not update the state. I tried using the default CoinScreen to see if I did something wrong, but not even the default page does not update either. I updated the libs packages to recent versions so I'm not sure if that broke something, or it's an internal issue. Thank you for the time and template.

**Comment by RudolfHladik** [comment]
Hello @Michael24884, 
can you share your code of the UseCase, the ViewModel and the Screen? If you push the data from the UseCase to the State and the State is observed in Composable function, everything should work. Does the clean Template project work for you?
